### ISSUE TITLE
Cannot create the xar file

### ISSUE THREAD

**Issue by fmaas90** [eXist-db/expath-file-module#5]
While trying to install the module with the cmd.exe I get the following exception while creating the xar file with `mvn clean compile package`:

```
[INFO] --- kuberam-expath-plugin:0.4.9:make-xar (create-xar) @ expath-file-module ---
[INFO] descriptorsDirectoryPath: C:\Users\Felix\exquery\expath-file-module\target\expath-descriptors-ec0aa038-6449-4342-a5d1-09995b44b11f
mavenResourcesExecution: org.apache.maven.shared.filtering.MavenResourcesExecution@5ab0b773
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource to C:\Users\Felix\exquery\expath-file-module\target\make-xar-tmp
[INFO] Resolved artifact: org.exist-db.xquery.extensions.expath:expath-file-module:jar:1.0-SNAPSHOT
[INFO] artifactFile: C:\Users\Felix\exquery\expath-file-module\target\expath-file-module-1.0-SNAPSHOT.jar
java.io.FileNotFoundException: \\C\Users\Felix\exquery\expath-file-module\target\expath-file-module-1.0-SNAPSHOT.jar
```

Could imagine why this is happening. The file expath-file-module-1.0-SNAPSHOT.jar exists but it lays in the path `C:\...` not in `\\C\...` Don't know why it is searched on `\\C\ `

**Comment by adamretter** [comment]
@fmaas90 I believe this is a known issue in the underlying plugin which needs to be fixed there, I am going to close this issue here as it should be dealt with here: https://github.com/claudius108/kuberam-expath-plugin/issues/1
